"""
Module containing the BindingPipeline class.

This module coordinates the generation of bridge and binding files required
to expose generated code to Python.
"""

from pathlib import Path

from .models.core import ModuleHeader
from .printers.cpythoncode import CPythonCodePrinter
from .printers.fcode import FCodePrinter
from .bindings.c_to_python import CPythonBindingGenerator
from .bridges.fortran_to_c import FortranToCBridgeGenerator

_EXTENSIONS = {"fortran": "f90", "c": "c"}
_HEADER_EXTENSIONS = {"fortran": None, "c": "h"}

binding_pipeline_registry = {
    "fortran": [FortranToCBridgeGenerator, CPythonBindingGenerator],
}

printer_registry = {
    FortranToCBridgeGenerator: FCodePrinter,
    CPythonBindingGenerator: CPythonCodePrinter,
}


class BindingPipeline:
    """
    Pipeline responsible for generating bridge and binding files.

    Parameters
    ----------
    codegen : Codegen
        The code generator which produced the translated AST.
    name : str
        Name of the generated module or program.
    language : str
        Source language accepted by the runtime wrapper pipeline.
    verbose : int
        The level of verbosity.
    """

    def __init__(self, codegen, name, language, verbose):
        self._ast = codegen.ast
        self._name = name
        self._verbose = verbose
        self._generated_asts = []

        self._pipeline_steps = binding_pipeline_registry[language]
        self._printer_types = [printer_registry[w] for w in self._pipeline_steps]
        self._additional_imports = [{} for _ in self._pipeline_steps]

    def generate(self, sharedlib_dirpath):
        """
        Generate the bridge and binding ASTs.

        Run each step of the binding pipeline in order. Each step receives the AST
        generated by the previous step and returns a new AST.


        Parameters
        ----------
        sharedlib_dirpath : str
            The folder where the generated .so file will be located.
        """
        ast = self._ast
        for Step in self._pipeline_steps:
            if self._verbose:
                print(
                    f">> Building {Step.start_language}-{Step.target_language} interface :: ",
                    self._name,
                )

            step = Step(sharedlib_dirpath, verbose=self._verbose)

            ast = step.generate(ast)
            self._generated_asts.append(ast)

    def write(self, dirpath):
        """
        Write the generated bridge and binding source files.

        Write the AST objects generated by a call to generate().

        Parameters
        ----------
        dirpath : str | Path
            The path to the directory where files should be printed.

        Returns
        -------
        list[Path]
            A list of the source files printed by this function (this is not equivalent
            to all files printed by this function as headers are excluded).
        """
        dirpath = Path(dirpath)
        files = [
            dirpath / f"{ast.name}_wrapper.{_EXTENSIONS[Step.start_language.lower()]}"
            for ast, Step in zip(self._generated_asts, self._pipeline_steps, strict=False)
        ]
        for i, (filepath, ast, Printer) in enumerate(
            zip(files, self._generated_asts, self._printer_types, strict=False)
        ):
            header_ext = _HEADER_EXTENSIONS[Printer.language.lower()]

            if self._verbose:
                print(">>> Printing :: ", filepath)
            printer = Printer(ast.name, verbose=self._verbose)
            # print module
            code = printer.doprint(ast)

            with open(filepath, "w", encoding="utf-8") as f:
                f.write(code)

            # print module header
            if header_ext is not None:
                header_filename = dirpath / f"{ast.name}_wrapper.{header_ext}"
                module_header = ModuleHeader(ast)
                if self._verbose:
                    print(">>> Printing :: ", header_filename)
                code = printer.doprint(module_header)
                with open(header_filename, "w", encoding="utf-8") as f:
                    f.write(code)

            self._additional_imports[i] = printer.get_additional_imports().copy()

        return files

    def get_additional_imports(self):
        """
        Get the objects that were imported by the codeprinters.

        Get the objects that were imported by the codeprinters.
        These imports may affect the necessary compiler commands.

        Returns
        -------
        list[dict[str, Import]]
            A dictionary for each printed wrapper file,
            mapping the include strings to the import module.
        """
        return self._additional_imports

    @property
    def generated_languages(self):
        """
        Get the languages of the generated bridge and binding files.
        """
        return [Printer.language.lower() for Printer in self._printer_types]
