      INTEGER FUNCTION CHAR_CODE_DEFAULT(C)
      CHARACTER C
      CHAR_CODE_DEFAULT = ICHAR(C)
      RETURN
      END

      INTEGER FUNCTION CHAR_CODE_STAR1(C)
      CHARACTER*1 C
      CHAR_CODE_STAR1 = ICHAR(C)
      RETURN
      END

      INTEGER FUNCTION STRING_LEN_STAR8(TEXT)
      CHARACTER*8 TEXT
      STRING_LEN_STAR8 = LEN_TRIM(TEXT)
      RETURN
      END

      INTEGER FUNCTION STRING_LEN_ASSUMED(TEXT)
      CHARACTER*(*) TEXT
      STRING_LEN_ASSUMED = LEN(TEXT)
      RETURN
      END

      INTEGER FUNCTION STRING_LEN_ENTITY(TEXT)
      CHARACTER TEXT*6
      STRING_LEN_ENTITY = LEN_TRIM(TEXT)
      RETURN
      END

      CHARACTER FUNCTION CHAR_RESULT_DEFAULT()
      CHAR_RESULT_DEFAULT = 'L'
      RETURN
      END

      CHARACTER*8 FUNCTION STRING_RESULT_STAR8()
      STRING_RESULT_STAR8 = 'LEGACY!!'
      RETURN
      END

      CHARACTER*8 FUNCTION STRING_RESULT_PADDED()
      STRING_RESULT_PADDED = 'PAD'
      RETURN
      END

      FUNCTION STRING_RESULT_DECLARED()
      CHARACTER*6 STRING_RESULT_DECLARED
      STRING_RESULT_DECLARED = 'STRING'
      RETURN
      END
