def char_code_default(
    c: Const(String[1])
) -> Int32: ...

def char_code_len1(
    c: Const(String[1])
) -> Int32: ...

def char_code_kind1(
    c: Const(String[1])
) -> Int32: ...

def char_code_c_char(
    c: Const(String[1])
) -> Int32: ...

def string_len_fixed(
    text: Const(String[8])
) -> Int32: ...

def string_len_assumed(
    text: Const(String)
) -> Int32: ...

def string_len_c_char(
    text: Const(String[8])
) -> Int32: ...

def char_result_default() -> String[1]: ...

def char_result_c_char() -> String[1]: ...

def string_result_fixed() -> String[8]: ...

def string_result_padded() -> String[8]: ...

def string_result_c_char() -> String[8]: ...

def string_result_deferred(
    text: Const(String)
) -> Annotated[String, FortranAllocatable]: ...
