"""Direct wrapper-plan generation infrastructure."""

from __future__ import annotations

from .c.binding import CBindingGenerator
from .fortran.bridge import FortranBridgeGenerator
from .generator import WrapperCodeGenerator
from .nodes import (
    BackendScalarType,
    CAllowThreadsBegin,
    CAllowThreadsEnd,
    CDeclaration,
    CExpressionStatement,
    CFunction,
    CFunctionPrototype,
    CHeader,
    CIf,
    CInclude,
    CMacroDefinition,
    CMethodDefEntry,
    CMethodDefTable,
    CModule,
    CModuleDef,
    CModulePropertyEntry,
    CModulePropertySupport,
    CParameter,
    CReturn,
    CodeExpression,
    FortranAssignment,
    FortranCall,
    FortranCase,
    FortranDeclaration,
    FortranFunction,
    FortranIf,
    FortranInterface,
    FortranInterfaceProcedure,
    FortranModule,
    FortranParameter,
    FortranPointerAssignment,
    FortranSelectCase,
    FortranUse,
)
from .plan import (
    ArgumentTransferPlan,
    ArrayHandoffPlan,
    BindingArgumentPlan,
    BindingFunctionPlan,
    BindingLifecyclePlan,
    BindingModulePlan,
    BindingModuleVariablePlan,
    BindingResultPlan,
    BindingStatusErrorPlan,
    BridgeArgumentPlan,
    BridgeFunctionPlan,
    BridgeLifecyclePlan,
    BridgeModulePlan,
    BridgeModuleVariablePlan,
    BridgeResultPlan,
    DatatypeFamily,
    FunctionPlan,
    LifecycleActionPlan,
    ModulePlan,
    ModuleVariablePlan,
    NativeCallSlotPlan,
    NamespacePlan,
    ResultPlan,
    WrapperPlanDiagnostic,
    WrapperPlanSupportBlocker,
    WrapperPlanSupportReport,
)
from .planner import WrapperPlanner
from .primitive_scalar_types import PrimitiveScalarTypeRegistry
from .source_printers import CSourcePrinter, FortranSourcePrinter
from .support import WrapperPlanSupportAnalyzer
from .visitor import ClassVisitor, UnsupportedWrapperCodegenNodeError

__all__ = (
    "ArgumentTransferPlan",
    "ArrayHandoffPlan",
    "BackendScalarType",
    "BindingArgumentPlan",
    "BindingFunctionPlan",
    "BindingLifecyclePlan",
    "BindingModulePlan",
    "BindingModuleVariablePlan",
    "BindingResultPlan",
    "BindingStatusErrorPlan",
    "BridgeArgumentPlan",
    "BridgeFunctionPlan",
    "BridgeLifecyclePlan",
    "BridgeModulePlan",
    "BridgeModuleVariablePlan",
    "BridgeResultPlan",
    "CAllowThreadsBegin",
    "CAllowThreadsEnd",
    "CBindingGenerator",
    "CDeclaration",
    "CExpressionStatement",
    "CFunction",
    "CFunctionPrototype",
    "CHeader",
    "CIf",
    "CInclude",
    "CMacroDefinition",
    "CMethodDefEntry",
    "CMethodDefTable",
    "CModule",
    "CModuleDef",
    "CModulePropertyEntry",
    "CModulePropertySupport",
    "CParameter",
    "CReturn",
    "CSourcePrinter",
    "ClassVisitor",
    "CodeExpression",
    "DatatypeFamily",
    "FortranAssignment",
    "FortranBridgeGenerator",
    "FortranCall",
    "FortranCase",
    "FortranDeclaration",
    "FortranFunction",
    "FortranIf",
    "FortranInterface",
    "FortranInterfaceProcedure",
    "FortranModule",
    "FortranParameter",
    "FortranPointerAssignment",
    "FortranSelectCase",
    "FortranSourcePrinter",
    "FortranUse",
    "FunctionPlan",
    "LifecycleActionPlan",
    "ModulePlan",
    "ModuleVariablePlan",
    "NamespacePlan",
    "NativeCallSlotPlan",
    "PrimitiveScalarTypeRegistry",
    "ResultPlan",
    "UnsupportedWrapperCodegenNodeError",
    "WrapperCodeGenerator",
    "WrapperPlanDiagnostic",
    "WrapperPlanSupportAnalyzer",
    "WrapperPlanSupportBlocker",
    "WrapperPlanSupportReport",
    "WrapperPlanner",
)
